CREATE USER IF NOT EXISTS 'admin_exer'@'%' IDENTIFIED BY 'password';
CREATE USER IF NOT EXISTS'app_exerotp'@'localhost' IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON *.* TO 'admin_exer'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON 'exer_db'.* TO 'app_exerotp'@'localhost';

FLUSH PRIVILEGES;

DROP USER IF EXISTS 'mysql'@'localhost';

SYSTEM mariadb -u admin_exer -ppassword;

DROP USER IF EXISTS 'root'@'localhost';

EXIT